name: cybergym
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - numpy>=1.21.0
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - pandas>=1.5.0
  - scipy>=1.9.0
  - tqdm>=4.64.0
  - pyyaml>=6.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - pytest>=7.2.0
  - pytest-cov>=4.0.0
  - black>=23.0.0
  - isort>=5.11.0
  - flake8>=6.0.0
  - mypy>=1.0.0
  - pre-commit>=3.0.0
  - pip:
    - gymnasium>=0.28.0
    - stable-baselines3>=2.0.0
    - tensorboard>=2.11.0
    - wandb>=0.15.0
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0